name: Scheduled Workflow

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:   # 👈 add this

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "This runs on schedule!"
